name: mars_weather_dash_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - plotly
  - altair
  - shiny
  - jupyterlab
  - ipykernel
  - scipy
  - pytest
  - pip
  - matplotlib
